# -*- coding: utf-8 -*-
"""LLMVS-Implementation-TVSum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5gvE4iZntKdhqGgo5PztgmDwJ7rHptt
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Colab-LLMVS/

# In Google Colab - install only non-PyTorch dependencies
!pip install numpy scipy pandas einops torchmetrics
!pip install matplotlib tqdm tensorboard h5py
!pip install pytorch-lightning>=2.0.0

# run this BEFORE train.py
import os

# Create checkpoint directories
os.makedirs('Summaries/tvsum_head2_layer3/tvsum/tvsum_split0/best_rho_model', exist_ok=True)
os.makedirs('Summaries/tvsum_head2_layer3/tvsum/tvsum_split0/best_tau_model', exist_ok=True)

print("✓ Checkpoint directories created")

# Training one split only
!python train.py --tag tvsum_split0 --model tvsum_head2_layer3 --lr 0.00007 --epochs 200 --dataset tvsum --reduced_dim 2048 --num_heads 2 --num_layers 3 --split_idx 0 --pt_path 'llama_emb/tvsum_sum/'

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# cp -r /content/best_rho_model /content/drive/MyDrive/Colab-LLMVS/Summaries/
# cp -r /content/best_tau_model /content/drive/MyDrive/Colab-LLMVS/Summaries/

!python test_splits.py --dataset tvsum --weights rho



# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab-LLMVS
!python test.py \
    --dataset tvsum \
    --split_idx 0 \
    --weights Summaries/best_rho_model/epoch=143-val_sRho=0.232.ckpt \
    --pt_path llama_emb/tvsum_sum/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab-LLMVS

!python save_frame_indices.py \
    --weights Summaries/tvsum_head2_layer3/tvsum/tvsum_split0/best_rho_model/epoch=53-val_sRho=0.230.ckpt \
    --pt_path llama_emb/tvsum_sum/ \
    --dataset tvsum \
    --split_idx 0 \
    --model tvsum_head2_layer3 \
    --tag tvsum_split0 \
    --output_json tvsum_frame_indices_with_scores.json

#The paths for videos has to be updated while running below
!python create_summary_video.py \
    --json_path tvsum_frame_indices_with_scores.json \
    --h5_path TVSum/eccv16_dataset_tvsum_google_pool5.h5 \
    --video_dir /Users/konda/Downloads/Fall_2025/NLP/Project2/Colab-LLMVS/datasets/tvsum50_ver_1_1/ydata-tvsum50-v1_1/video \
    --video_key video_45 \
    --output video_45_summary.mp4